FROM internetee/ruby_base:3.0
LABEL org.opencontainers.image.source=https://github.com/internetee/rest-whois
ARG RAILS_ENV

ENV RAILS_ENV "$RAILS_ENV"

COPY Gemfile Gemfile.lock ./    
RUN gem install bundler && bundle config set without 'development test' && bundle install --jobs 20 --retry 5

COPY . .
RUN bundle exec rails assets:precompile