ARG RUBY_VERSION=3.4.9
FROM ruby:${RUBY_VERSION}-bookworm

WORKDIR /opt/webapps/app

ENV RAILS_ENV="production" \
    RAILS_LOG_TO_STDOUT=true \
    BUNDLE_DEPLOYMENT="1" \
    BUNDLE_PATH="/usr/local/bundle" \
    LANG=et_EE.UTF-8 \
    LANGUAGE=et_EE:et \
    LC_ALL=et_EE.UTF-8

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    netcat-openbsd \
    curl \
    libpq-dev \
    nodejs \
    imagemagick \
    shared-mime-info \
    locales \
    && echo "et_EE.UTF-8 UTF-8" > /etc/locale.gen \
    && locale-gen \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY Gemfile Gemfile.lock ./
RUN bundle config set --local without 'development test' && \
    bundle install --jobs 20 --retry 5 && \
    bundle clean --force

COPY . .

RUN RAILS_ENV=production bundle exec rake assets:precompile

EXPOSE 3000

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
