default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:

development:
  <<: *default
  database: rest_whois_development

test:
  <<: *default
  database: rest_whois_test

production:
  <<: *default
  database: rest_whois_production
