default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("APP_DB_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("APP_DBHOST") { "localhost" } %>
  username: <%= ENV.fetch("APP_DBUSER") { "postgres" } %>
  password:

development:
  <<: *default
  database: rest_whois_development

test:
  <<: *default
  database: rest_whois_test

production:
  <<: *default
  database: rest_whois_production

# Our production environment use two separate databases for different models. WhoisRecord are
# read-only, while ContactRequests need write access. To enable access to second database,
# ucommment the following lines.
# You can also define write_development, or write_test databases, depending on your needs
# write_production:
#   <<: *default
#   database: rest_whois_production
