default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  username:
  password:

development:
  <<: *default
  database: rest_whois_development

test:
  <<: *default
  database: rest_whois_test

# Our production environment use two separate databases for different models.
# WhoisRecord are read-only, while ContactRequests need write access to
production_read_only:
  <<: *default
  database: rest_whois_production

production_write:
  <<: *default
  database: rest_whois_production
