default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("APP_DB_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("APP_DBHOST") { "localhost" } %>
  username: <%= ENV.fetch("APP_DBUSER") { "postgres" } %>
  password:

development:
  <<: *default
  database: rest_whois_development

test:
  <<: *default
  database: rest_whois_test

production:
  <<: *default
  database: rest_whois_production
